edition = 1
exports = []

[package]
name = "android-echo-client"
description = "Android Echo Client"

[package.actr_type]
manufacturer = "acme"
name = "echo-client-app"
authors = []
license = "Apache-2.0"
tags = ["dev", "example", "android"]

[dependencies]

[system.signaling]
url = "ws://124.71.231.251:9080/signaling/ws"

[system.deployment]
realm = 2368266035

[system.discovery]
visible = false

[system.observability]
filter_level = "info"
tracing_enabled = false
tracing_endpoint = "http://localhost:4317"
tracing_service_name = "android-echo-client"

[system.webrtc]
force_relay = true
stun_urls = ["stun:124.71.231.251:13478"]
turn_urls = ["turn:124.71.231.251:13478"]

# ACL configuration
[acl]

[[acl.rules]]
permission = "allow"
types = ["acme+EchoService", "acme+FileTransferService"]

[scripts]
